import argparse
from pathlib import Path

# Focused optimization currently builds only the exact head-64 target.
HEAD_DIMS = (64,)
CONFIGS = (
    (64, 128, 8, 32, 64, "dynamic"),
    (64, 128, 8, 32, 64, "power2_ds"),
    (64, 128, 8, 32, 64, "periodic_ds"),
)
POLICY_EXPRESSIONS = {
    "dynamic": "BwdQuantizationPolicy::kDynamic",
    "power2_ds": "BwdQuantizationPolicy::kPowerOfTwoDs",
    "periodic_ds": "BwdQuantizationPolicy::kPeriodicDs",
}
POLICY_IDS = {"dynamic": 0, "power2_ds": 1, "periodic_ds": 2}
GENERATED_DIR = Path("csrc/qattn_cutlass/generated")
DISPATCH_HEADER = "qk_int8_sv_f16_accum_f32_attn_bwd_cutlass_dispatch.cuh"
SOURCE_PREFIX = "qk_int8_sv_f16_accum_f32_attn_bwd_cutlass"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _config_suffix(config: tuple[int, int, int, int, int, str]) -> str:
    block_m, block_n, num_warps, blk_q, blk_k, policy = config
    policy_suffix = "" if policy == "dynamic" else f"_{policy}"
    return f"bm{block_m}_bn{block_n}_nw{num_warps}_bq{blk_q}_bk{blk_k}{policy_suffix}"


def _source_name(head_dim: int, config: tuple[int, int, int, int, int, str]) -> str:
    return f"{SOURCE_PREFIX}_hd{head_dim}_{_config_suffix(config)}.cu"


def _write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _signature(
    head_dim: int,
    block_m: int,
    block_n: int,
    num_warps: int,
    blk_q: int,
    blk_k: int,
    policy: str,
    prefix: str = "",
) -> str:
    policy_expression = POLICY_EXPRESSIONS[policy]
    return f"""\
{prefix}template void launch_mma<{head_dim}, {block_m}, {block_n}, {num_warps}, {blk_q}, {blk_k}, {policy_expression}>(
  const torch::stable::Tensor &query,
  const torch::stable::Tensor &key,
  const torch::stable::Tensor &query_scale,
  const torch::stable::Tensor &key_scale,
  const torch::stable::Tensor &value,
  const torch::stable::Tensor &output,
  const torch::stable::Tensor &grad_output,
  const torch::stable::Tensor &lse,
  const torch::stable::Tensor &grad_query,
  const torch::stable::Tensor &grad_key,
  const torch::stable::Tensor &grad_value,
  const Params &params,
  double sm_scale);"""


def _generated_source(root: Path, head_dim: int, config: tuple[int, int, int, int, int, str]) -> Path:
    path = root / GENERATED_DIR / _source_name(head_dim, config)
    block_m, block_n, num_warps, blk_q, blk_k, policy = config
    signature = _signature(head_dim, block_m, block_n, num_warps, blk_q, blk_k, policy)
    content = f"""\
// Generated by scripts/generate_cutlass_bwd_instantiations.py. Do not edit manually.

#define SAGEATTENTION_QATTN_CUTLASS_BWD_INSTANTIATION
#include \"../qk_int8_sv_f16_bwd_launch_cutlass_sm80.cuh\"

namespace sageattention::qattn_cutlass_bwd {{

{signature}

}} // namespace sageattention::qattn_cutlass_bwd
"""
    _write_if_changed(path, content)
    return path


def _dispatch_config(head_dim: int, config: tuple[int, int, int, int, int, str]) -> str:
    block_m, block_n, num_warps, blk_q, blk_k, policy = config
    policy_expression = POLICY_EXPRESSIONS[policy]
    policy_id = POLICY_IDS[policy]
    return f"""\
      if (params.blk_q == {blk_q} && params.blk_k == {blk_k} && params.bwd_block_m == {block_m} && params.bwd_block_n == {block_n} && params.quantization_policy == {policy_id})
      {{
        launch_mma<{head_dim}, {block_m}, {block_n}, {num_warps}, {blk_q}, {blk_k}, {policy_expression}>(query, key, query_scale, key_scale, value, output, grad_output, lse, grad_query, grad_key, grad_value, params, sm_scale);
        return;
      }}"""


def _dispatch_head(head_dim: int, configs: tuple[tuple[int, int, int, int, int, str], ...]) -> str:
    config_branches = "\n".join(_dispatch_config(head_dim, config) for config in configs)
    return f"""\
  if (params.head_dim == {head_dim})
  {{
{config_branches}
  }}"""


def _extern_declarations(configs: tuple[tuple[int, int, int, int, int, str], ...]) -> str:
    declarations = []
    for head_dim in HEAD_DIMS:
        for config in configs:
            block_m, block_n, num_warps, blk_q, blk_k, policy = config
            declarations.append(
                _signature(head_dim, block_m, block_n, num_warps, blk_q, blk_k, policy, prefix="extern ")
            )
    return "\n\n".join(declarations)


def _write_dispatch(root: Path, configs: tuple[tuple[int, int, int, int, int, str], ...]) -> Path:
    path = root / GENERATED_DIR / DISPATCH_HEADER
    externs = _extern_declarations(configs)
    head_branches = "\n".join(_dispatch_head(head_dim, configs) for head_dim in HEAD_DIMS)
    content = f"""\
// Generated by scripts/generate_cutlass_bwd_instantiations.py. Do not edit manually.

#pragma once

#include <stdexcept>

namespace sageattention::qattn_cutlass_bwd {{

{externs}

inline void launch_configured_mma(const torch::stable::Tensor &query,
                                  const torch::stable::Tensor &key,
                                  const torch::stable::Tensor &query_scale,
                                  const torch::stable::Tensor &key_scale,
                                  const torch::stable::Tensor &value,
                                  const torch::stable::Tensor &output,
                                  const torch::stable::Tensor &grad_output,
                                  const torch::stable::Tensor &lse,
                                  const torch::stable::Tensor &grad_query,
                                  const torch::stable::Tensor &grad_key,
                                  const torch::stable::Tensor &grad_value,
                                  const Params &params,
                                  const double sm_scale)
{{
{head_branches}

  throw std::invalid_argument(\"Unsupported CUTLASS qattn backward block config\");
}}

}} // namespace sageattention::qattn_cutlass_bwd
"""
    _write_if_changed(path, content)
    return path


def _remove_stale_sources(root: Path, generated: set[Path]) -> None:
    generated_dir = root / GENERATED_DIR
    if not generated_dir.exists():
        return
    for path in generated_dir.glob(f"{SOURCE_PREFIX}_hd*_bm*_bn*_nw*.cu"):
        if path not in generated:
            path.unlink()


def generate(root: str | Path | None = None) -> list[Path]:
    root = Path(root) if root is not None else _repo_root()
    root = root.resolve()

    sources = []
    for head_dim in HEAD_DIMS:
        for config in CONFIGS:
            sources.append(_generated_source(root, head_dim, config))

    _write_dispatch(root, CONFIGS)
    _remove_stale_sources(root, set(sources))
    return sources


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CUTLASS qattn backward kernel instantiation files.")
    parser.add_argument("--root", type=Path, default=_repo_root(), help="Repository root")
    parser.add_argument("--list-sources", action="store_true", help="Print generated source paths")
    args = parser.parse_args()

    sources = generate(args.root)
    if args.list_sources:
        root = args.root.resolve()
        for path in sources:
            print(path.relative_to(root))


if __name__ == "__main__":
    main()
