import argparse
import ast
from pathlib import Path
from typing import cast

HEAD_DIMS = (64, 128)
RETURN_LSE = (False, True)
GENERATED_DIR = Path("csrc/qattn_cutlass/generated")
DISPATCH_HEADER = "qk_int8_sv_f16_accum_f32_attn_cutlass_dispatch.cuh"
SOURCE_PREFIX = "qk_int8_sv_f16_accum_f32_attn_cutlass"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _read_autotune_configs(root: Path) -> tuple[tuple[int, int, int, int], ...]:
    path = root / "sageattention" / "cutlass_autotune.py"
    module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in module.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "_AUTOTUNE_CONFIGS":
                    configs = ast.literal_eval(node.value)
                    return tuple(
                        cast(tuple[int, int, int, int], tuple(int(value) for value in config)) for config in configs
                    )
    raise RuntimeError(f"Could not find _AUTOTUNE_CONFIGS in {path}")


def _config_suffix(config: tuple[int, int, int, int]) -> str:
    blk_q, blk_k, warp_q, warp_k = config
    return f"bq{blk_q}_bk{blk_k}_wq{warp_q}_wk{warp_k}"


def _source_name(head_dim: int, config: tuple[int, int, int, int]) -> str:
    return f"{SOURCE_PREFIX}_hd{head_dim}_{_config_suffix(config)}.cu"


def _write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _generated_source(root: Path, head_dim: int, config: tuple[int, int, int, int]) -> Path:
    path = root / GENERATED_DIR / _source_name(head_dim, config)
    blk_q, blk_k, warp_q, warp_k = config
    content = f"""\
// Generated by scripts/generate_cutlass_fwd_instantiations.py. Do not edit manually.

#include \"../qk_int8_sv_f16_launch_cutlass_sm80.cuh\"

template void sageattention::qattn_cutlass::launch_kernel<{head_dim}, {blk_q}, {blk_k}, {warp_q}, {warp_k}, false>(
  const sageattention::qattn_cutlass::LaunchParams &params);

template void sageattention::qattn_cutlass::launch_kernel<{head_dim}, {blk_q}, {blk_k}, {warp_q}, {warp_k}, true>(
  const sageattention::qattn_cutlass::LaunchParams &params);
"""
    _write_if_changed(path, content)
    return path


def _dispatch_config(head_dim: int, return_lse: bool, config: tuple[int, int, int, int]) -> str:
    blk_q, blk_k, warp_q, warp_k = config
    lse = "true" if return_lse else "false"
    return f"""\
      if (params.blk_q == {blk_q} && params.blk_k == {blk_k} && params.warp_q == {warp_q} && params.warp_k == {warp_k})
      {{
        launch_kernel<{head_dim}, {blk_q}, {blk_k}, {warp_q}, {warp_k}, {lse}>(params);
        return;
      }}"""


def _dispatch_lse(head_dim: int, return_lse: bool, configs: tuple[tuple[int, int, int, int], ...]) -> str:
    config_branches = "\n".join(_dispatch_config(head_dim, return_lse, config) for config in configs)
    lse = "true" if return_lse else "false"
    return f"""\
    if (return_lse == {lse})
    {{
{config_branches}
    }}"""


def _dispatch_head(head_dim: int, configs: tuple[tuple[int, int, int, int], ...]) -> str:
    lse_branches = "\n".join(_dispatch_lse(head_dim, return_lse, configs) for return_lse in RETURN_LSE)
    return f"""\
  if (params.head_dim == {head_dim})
  {{
{lse_branches}
  }}"""


def _write_dispatch(root: Path, configs: tuple[tuple[int, int, int, int], ...]) -> Path:
    path = root / GENERATED_DIR / DISPATCH_HEADER
    head_branches = "\n".join(_dispatch_head(head_dim, configs) for head_dim in HEAD_DIMS)
    content = f"""\
// Generated by scripts/generate_cutlass_fwd_instantiations.py. Do not edit manually.

#pragma once

#include <stdexcept>

namespace sageattention::qattn_cutlass {{

inline void launch_configured_kernel(const LaunchParams &params, const bool return_lse)
{{
{head_branches}

  throw std::invalid_argument(\"Unsupported CUTLASS qattn block config\");
}}

}} // namespace sageattention::qattn_cutlass
"""
    _write_if_changed(path, content)
    return path


def _remove_stale_sources(root: Path, generated: set[Path]) -> None:
    generated_dir = root / GENERATED_DIR
    if not generated_dir.exists():
        return
    for path in generated_dir.glob(f"{SOURCE_PREFIX}_hd*_bq*_bk*_wq*_wk*.cu"):
        if path not in generated:
            path.unlink()


def generate(root: str | Path | None = None) -> list[Path]:
    root = Path(root) if root is not None else _repo_root()
    root = root.resolve()
    configs = _read_autotune_configs(root)

    sources = []
    for head_dim in HEAD_DIMS:
        for config in configs:
            sources.append(_generated_source(root, head_dim, config))

    _write_dispatch(root, configs)
    _remove_stale_sources(root, set(sources))
    return sources


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CUTLASS qattn forward kernel instantiation files.")
    parser.add_argument("--root", type=Path, default=_repo_root(), help="Repository root")
    parser.add_argument("--list-sources", action="store_true", help="Print generated source paths")
    args = parser.parse_args()

    sources = generate(args.root)
    if args.list_sources:
        root = args.root.resolve()
        for path in sources:
            print(path.relative_to(root))


if __name__ == "__main__":
    main()
