import argparse
from pathlib import Path

# Focused optimization currently builds only the exact head-64 target.
HEAD_DIMS = (64,)
CONFIGS = ((64, 128, 8, 32, 64),)
GENERATED_DIR = Path("csrc/qattn_cutlass/generated")
DISPATCH_HEADER = "qk_int8_sv_f16_accum_f32_attn_bwd_cutlass_dispatch.cuh"
SOURCE_PREFIX = "qk_int8_sv_f16_accum_f32_attn_bwd_cutlass"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _config_suffix(config: tuple[int, int, int, int, int]) -> str:
    block_m, block_n, num_warps, blk_q, blk_k = config
    return f"bm{block_m}_bn{block_n}_nw{num_warps}_bq{blk_q}_bk{blk_k}"


def _source_name(head_dim: int, config: tuple[int, int, int, int, int]) -> str:
    return f"{SOURCE_PREFIX}_hd{head_dim}_{_config_suffix(config)}.cu"


def _write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def _signature(
    head_dim: int,
    block_m: int,
    block_n: int,
    num_warps: int,
    blk_q: int,
    blk_k: int,
    prefix: str = "",
) -> str:
    return f"""\
{prefix}template void launch_mma<{head_dim}, {block_m}, {block_n}, {num_warps}, {blk_q}, {blk_k}>(
  const torch::stable::Tensor &query,
  const torch::stable::Tensor &key,
  const torch::stable::Tensor &query_scale,
  const torch::stable::Tensor &key_scale,
  const torch::stable::Tensor &value,
  const torch::stable::Tensor &output,
  const torch::stable::Tensor &dO,
  const torch::stable::Tensor &lse,
  const torch::stable::Tensor &delta,
  const torch::stable::Tensor &dQ_accum,
  const torch::stable::Tensor &dO_int8,
  const torch::stable::Tensor &dO_scale,
  const torch::stable::Tensor &dS_q_factors,
  const torch::stable::Tensor &dS_k_factors,
  const torch::stable::Tensor &dQ,
  const torch::stable::Tensor &dK,
  const torch::stable::Tensor &dV,
  const Params &params,
  double sm_scale);"""


def _generated_source(root: Path, head_dim: int, config: tuple[int, int, int, int, int]) -> Path:
    path = root / GENERATED_DIR / _source_name(head_dim, config)
    block_m, block_n, num_warps, blk_q, blk_k = config
    signature = _signature(head_dim, block_m, block_n, num_warps, blk_q, blk_k)
    content = f"""\
// Generated by scripts/generate_cutlass_bwd_instantiations.py. Do not edit manually.

#define SAGEATTENTION_QATTN_CUTLASS_BWD_INSTANTIATION
#include "../qk_int8_sv_f16_bwd_launch_cutlass_sm80.cuh"

namespace sageattention::qattn_cutlass_bwd {{

{signature}

}} // namespace sageattention::qattn_cutlass_bwd
"""
    _write_if_changed(path, content)
    return path


def _dispatch_config(head_dim: int, config: tuple[int, int, int, int, int]) -> str:
    block_m, block_n, num_warps, blk_q, blk_k = config
    return f"""\
      if (params.blk_q == {blk_q} && params.blk_k == {blk_k} && params.bwd_block_m == {block_m} && params.bwd_block_n == {block_n})
      {{
        launch_mma<{head_dim}, {block_m}, {block_n}, {num_warps}, {blk_q}, {blk_k}>(query, key, query_scale, key_scale, value, output, dO, lse, delta, dQ_accum, dO_int8, dO_scale, dS_q_factors, dS_k_factors, dQ, dK, dV, params, sm_scale);
        return;
      }}"""


def _dispatch_head(head_dim: int, configs: tuple[tuple[int, int, int, int, int], ...]) -> str:
    config_branches = "\n".join(_dispatch_config(head_dim, config) for config in configs)
    return f"""\
  if (params.head_dim == {head_dim})
  {{
{config_branches}
  }}"""


def _extern_declarations(configs: tuple[tuple[int, int, int, int, int], ...]) -> str:
    declarations = []
    for head_dim in HEAD_DIMS:
        for config in configs:
            declarations.append(_signature(head_dim, *config, prefix="extern "))
    return "\n\n".join(declarations)


def _write_dispatch(root: Path, configs: tuple[tuple[int, int, int, int, int], ...]) -> Path:
    path = root / GENERATED_DIR / DISPATCH_HEADER
    externs = _extern_declarations(configs)
    head_branches = "\n".join(_dispatch_head(head_dim, configs) for head_dim in HEAD_DIMS)
    content = f"""\
// Generated by scripts/generate_cutlass_bwd_instantiations.py. Do not edit manually.

#pragma once

#include <stdexcept>

namespace sageattention::qattn_cutlass_bwd {{

{externs}

inline void launch_configured_mma(const torch::stable::Tensor &query,
                                  const torch::stable::Tensor &key,
                                  const torch::stable::Tensor &query_scale,
                                  const torch::stable::Tensor &key_scale,
                                  const torch::stable::Tensor &value,
                                  const torch::stable::Tensor &output,
                                  const torch::stable::Tensor &dO,
                                  const torch::stable::Tensor &lse,
                                  const torch::stable::Tensor &delta,
                                  const torch::stable::Tensor &dQ_accum,
                                  const torch::stable::Tensor &dO_int8,
                                  const torch::stable::Tensor &dO_scale,
                                  const torch::stable::Tensor &dS_q_factors,
                                  const torch::stable::Tensor &dS_k_factors,
                                  const torch::stable::Tensor &dQ,
                                  const torch::stable::Tensor &dK,
                                  const torch::stable::Tensor &dV,
                                  const Params &params,
                                  const double sm_scale)
{{
{head_branches}

  throw std::invalid_argument("Unsupported CUTLASS qattn backward block config");
}}

}} // namespace sageattention::qattn_cutlass_bwd
"""
    _write_if_changed(path, content)
    return path


def _remove_stale_sources(root: Path, generated: set[Path]) -> None:
    generated_dir = root / GENERATED_DIR
    if not generated_dir.exists():
        return
    for path in generated_dir.glob(f"{SOURCE_PREFIX}_hd*_bm*_bn*_nw*.cu"):
        if path not in generated:
            path.unlink()


def generate(root: str | Path | None = None) -> list[Path]:
    root = Path(root) if root is not None else _repo_root()
    root = root.resolve()

    sources = [_generated_source(root, head_dim, config) for head_dim in HEAD_DIMS for config in CONFIGS]
    _write_dispatch(root, CONFIGS)
    _remove_stale_sources(root, set(sources))
    return sources


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CUTLASS qattn backward kernel instantiation files.")
    parser.add_argument("--root", type=Path, default=_repo_root(), help="Repository root")
    parser.add_argument("--list-sources", action="store_true", help="Print generated source paths")
    args = parser.parse_args()

    sources = generate(args.root)
    if args.list_sources:
        root = args.root.resolve()
        for path in sources:
            print(path.relative_to(root))


if __name__ == "__main__":
    main()
